version: '3.4'

services:
  listingdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  listing.api:
    image: ${DOCKER_REGISTRY-}listingapi
    build:
      context: .
      dockerfile: Services/Listing/Listing.API/Dockerfile

  auth.api:
    image: ${DOCKER_REGISTRY-}authapi
    build:
      context: .
      dockerfile: Services/Auth/Auth.API/Dockerfile

  assetmanagement.api:
    image: ${DOCKER_REGISTRY-}assetmanagementapi
    build:
      context: .
      dockerfile: Services/AssetManagement/AssetManagement.API/Dockerfile

  booking.api:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Services/Booking/Booking.API/Dockerfile

volumes:
  postgres_data:
  pgadmin_data:



